# cauldron/geasa/yarn/pod.yml
# Configuration du service Yarn pour Dagda-Lite
# Gestionnaire de paquets Node.js

apiVersion: v1
kind: Pod
metadata:
  name: dagda-lite-yarn-pod
spec:
  containers:
  - name: dagda-lite-yarn
    image: node:18-alpine
    ports:
    - containerPort: 8907
      hostPort: ${YARN_PORT}
    - containerPort: 8900
      hostPort: 8900
    env:
    - name: NODE_ENV
      value: "development"
    - name: YARN_CACHE_FOLDER
      value: "/yarn-cache"
    volumeMounts:
    - name: yarn-data
      mountPath: /yarn-cache
    - name: yarn-config
      mountPath: /usr/local/share/.config/yarn
    command: ["sh", "-c", "tail -f /dev/null"]
  volumes:
  - name: yarn-data
    hostPath:
      path: ${GEASA_DIR}/yarn/data
      type: DirectoryOrCreate
  - name: yarn-config
    hostPath:
      path: ${GEASA_DIR}/yarn/config
      type: DirectoryOrCreate
  restartPolicy: Always
